<?php
/* @var $block \Aheadworks\MobilePushNotification\Block\Adminhtml\Pushnotification\Previewnotification */
/* @var $escaper \Magento\Framework\Escaper */
?>

<?php $previewImage = $block::PREVIEW_IMAGE; ?>
<div class="preview-image">
    <div class="previewsection">
        <label id="previewtext"></label>
        <label id="previewmsg"></label>
    </div>
    <?php $imgUrl = $block->getViewFileUrl('Aheadworks_MobilePushNotification::'.$previewImage); ?>
    <image src='<?= $escaper->escapeUrl($imgUrl); ?>'/>
</div>